config/routes.rb
LivingDreamy::Application.routes.draw do
  root :to => 'dreams#index'
  resources :dreams

  get 'login' => 'sessions#create', :as => 'login'
end

app/models/dream.rb
class Dream < ActiveRecord::Base
  attr_accessible :description, :title

  validates :title, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :role
  after_create :update_name

  def update_name
    self.name = email.split('@').first.gsub('.',' ').titleize
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate!

  def authenticate!
    redirect_to login_path unless session[:user_id]
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def index
    @dreams = Dream.all
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(params[:dream])

    if @dream.save
      redirect_to dream_path(@dream)
    else
      render :new
    end
  end

  def edit
    @dream = Dream.find(params[:id])
  end

  def update
    @dream = Dream.find(params[:id])

    if @dream.update_attributes(params[:dream])
      redirect_to dream_path(@dream)
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate!

  def create
    google_apps_authenticate "hungrymachine.com", 'callback', [:email]
  end

  def destroy
    email = session.delete(:user_id)
    flash[:notice] = "Signed out."
    redirect_to new_session_path
  end

  def callback
    response = google_apps_handle_auth
    if response.failed? or response.canceled?
      flash[:notice] = "Could not authenticate: #{response.error}"
    else
      authorize(response[:email].first)
    end
  end

  private

  # Jonan: in this application you couldn't login (even if you could
  # authenticate through Google Apps) unless there was a User record
  # with your email address. If your application is more open, you
  # could just find or create by email instead.

  def authorize(email)
    authorized = User.find_or_create_by_email(email)

    if authorized
      flash[:notice] = "Signed in #{authorized.email}"
      session[:user_id] = authorized.id
      if session[:destination]
        destination = session.delete(:destination)
      else
        destination = root_path
      end
      redirect_to destination
    else
      flash[:error] = "You are not authorized for this application."
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_form.html.slim
= form_for(@dream) do |f|
  = f.text_field :title
  = f.text_area :description
  = f.submit

app/views/dreams/edit.html.slim
h1 Edit Dream

= render :partial => 'form'

app/views/dreams/index.html.slim
h1 Dreams

= link_to "I have a dream", new_dream_path, :id => 'new_dream'

#dreams
  - @dreams.each do |dream|
    .dream
      h3 = dream.title
      p = dream.description

app/views/dreams/new.html.slim
h1 New Dream

= render :partial => 'form'

app/views/dreams/show.html.slim
h1 = @dream.title

.description
  p = @dream.description

.votes
  span = @dream.votes

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LivingDreamy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>